### ISSUE TITLE
Thắc mắc: tại sao không merge với original repo

### ISSUE THREAD

**Issue by antranapp** [thanhphu/just-awesome-vietnamese#2]
Trước hết rất cám ơn bạn đã làm một repo thực sự hữu ích này.

Mình có một thắc mắc nho nhỏ là tại sao bạn không làm 1 PR để merge với original repo của bạn @virusvn ?

Mình sợ nhiều forks khác nhau thế này sẽ làm phân mảnh công việc tổng hợp các repos hay của dev việt mình.

**Comment by winstonleedev** [comment]
Uhm, lúc đầu mình đã fork vì tính đổi tên repo cho "hay" hơn nhưng bị ném đá nhiều quá :))

Mình tạo PR rồi chờ bạn virusvn đáp thôi https://github.com/virusvn/awesome-vietnamese/pull/3
